### ISSUE TITLE
Non existent folders assigned to artists + redundant scanning of non-set /music folder

### ISSUE THREAD

**Issue by janaxhell** [youegraillot/lidarr-on-steroids#10]
Hi, we spoke on reddit. For almost a week I tried to import my library because using lidarr.db didn't work.
My folder structure is 
/data/media/music/[genre folder]/artist
I have mounted 
/data/media/music:/music 
as I did in standard Lidarr.
In that case, until I added some root folders, Lidarr stayed idle. Only after adding some it started scanning them.

Now I have noticed 2 issues in lidarr-on-steroids that make this process so long and messed:
- lidarr-on-steroids scans /music folder no matter what, even if I haven't set it as root folder (I only use genre root folders inside /music) - This hogs memory as it seems it's duplicating the process of scanning both /music folder AND all the genre folders I have set.
- lidarr-on-steroids assigns non existent folders to artists presumably adding info from Musicbrainz

Example:
I have 
/data/media/music/Brit Pop/Blur
lidarr-on-steroids assigns Blur to
/data/media/music/Brit Pop/Blur (UK alternative rock band)
but that folder with that stuff between brackets does not exist.

Even more weird, while many artists with this same error show no available albums, others, like Blur themselves, show them all.
I have tried to Edit some of those not showing albums, and as soon as I removed the (stuff between brackets) from path, all albums appeared.

**Comment by youegraillot** [comment]
Ok, there are many problems here, and I believe some of them are not "lidarr-on-steroids" specifics but: 
- if your genre folder is in your root folder, I don't see a way not to scan these
- if `AUTOCONFIG` environment variable is true (default), your root folder will be overwritten with /music (see Readme for more info)
- the (stuff between brackets) is called disambiguation and Lidarr my use them if you explicitly set it to : settings/mediamanagement
- you may want to enable "Rename Tracks" to get rid of unwanted characters

**Comment by janaxhell** [comment]
Ok, I have set AUTOCONFIG to false and it seems to work: it still says it's scanning /data/media/music besides all the others, but doesn't hog memory. 
I have indeed noticed that there was a disambiguation tag set in media management, must have added while experimenting.
I have tried to search and download some albums: Deemix started downloading, but when it finished it got stuck on the purple icon "Waiting to import". All albums are in /data/media/downloads/music but they aren't moved to /data/media/music and when the last album finishes download, l-o-s hangs like in the picture and becomes unresponsive and logging in Portainer dies at the same moment, no more info appears afterwards.

![los](https://user-images.githubusercontent.com/55061479/180502905-4de6e986-488f-4327-acb7-437539a11a25.jpg)

**Comment by youegraillot** [comment]
What is your current root folder now ? ensure that Lidarr have both the corrects rights to write on /downloads and /music
also, do you see some relevant logs in system/events ?

**Comment by janaxhell** [comment]
I have 79 root folders named as genres, like
/data/media/music/Rock
/data/media/music/Blues
L-o-s is set as my user PUID/PGID 998/100 
/downloads and /music are both on a NTFS drive for which all containers have all access, standard Lidarr works fine with exact same paths.
This is the latest debug log as soon as it freezed:
[Lidarr.debug.txt](https://github.com/youegraillot/lidarr-on-steroids/files/9173247/Lidarr.debug.txt)

**Comment by janaxhell** [comment]
Hi, can you see anything useful in the log? I basically cannot use your app at all.

**Comment by janaxhell** [comment]
Ok, seems you're not very interested, anyway, I've reinstalled LOS for the Nth time, this time adding only 1 root folder which is inside /music.
Nevertheless it scanned both the entire /music content AND root folder. I patiently waited something like 12 hours to complete any activity. 
So I added all my indexers and SAB client and launched a search for all Wanted albums. It found 75, but when it finished download, instead of importing them, it started scanning AGAIN the entire /music folder. Then after finishing it simply idled doing nothing but RSS checks, with all albums downloaded by Deemix and SAB stuck as "Waiting to Import". This does not happen with standard Lidarr. I have switched to it and it works normal as always. As soon as albums are downloaded, it imports them one by one, it does not leave them all waiting, nor starts scanning the entire /music folder. 
Oh, and both /download and /music folders are chmod -R 777.

**Comment by youegraillot** [comment]
If you are unsatisfied, I'm sorry to read that and will gladly refund you for my support and time I spent building this.

In a more serious manner, this tool is not (yet) tested in conjunction with other clients and indexers and it now seems that this is the root cause of your conflicts when importing files. I'm planning to investigate this when I'll have some time after working on deezer integration as an indexer.

**Comment by janaxhell** [comment]
You asked to post logs then disappeared, that's all. 
I'm more than willing to help make this work the way I can, which is feedback.
