### ISSUE TITLE
Can't access webUI on Synology NAS

### ISSUE THREAD

**Issue by EXCIDIVM** [youegraillot/lidarr-on-steroids#11]
Installed everything and according to logs it seems to run fine.
But I can't log into the webUI - it just doesn't find a page. Problem with both, lidarr and deemix.
Works just fine with vanilla deemix and vanilla lidarr, which I both uninstalled before installing this.

Log:
`Executing usermod...

usermod: no changes

Applying permissions to /config

[cont-init.d] 00-start-container: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] Starting Deemix

Changing ownership on scripts.

----------------------------------------------------------------------

LIDARR SETUP

----------------------------------------------------------------------

PluginSource=https://github.com/ta264/Lidarr.Plugin.Deemix

----------------------------------------------------------------------

[autoconfig] Waiting Lidarr to launch on 8686...

[services.d] done.

2022-07-23T08:52:19.683Z [info] Listening on port 6595

[Info] Bootstrap: Starting Lidarr - /app/bin/Lidarr.dll - Version 1.1.0.2629 

[Debug] Bootstrap: Console selected 

[Info] AppFolderInfo: Data directory is being overridden to [/config] 

[Info] AppFolderInfo: Data directory is being overridden to [/config] 

[Debug] Microsoft.Extensions.Hosting.Internal.Host: Hosting starting 

[Info] AppFolderInfo: Data directory is being overridden to [/config] 

[Info] MigrationController: *** Migrating data source=/config/lidarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 

[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 

[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:8686 

[autoconfig] Waiting for /config_deemix/login.json to be filled...

[Info] RootFolderWatchingService: Watching directory /music 

[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 

[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 

[Info] Microsoft.Hosting.Lifetime: Content root path: /run/s6/services/lidarr `

**Comment by youegraillot** [comment]
Please share your fix so that others can follow your steps
