### ISSUE TITLE
Deemix logs out, when Deemix is logged back in Lidarr can't communicate with it

### ISSUE THREAD

**Issue by martind2000** [youegraillot/lidarr-on-steroids#12]
Hi, I have this recurring issue that Deemix logs out for some reason, and it takes a while to log back in. I've discovered that clearing the cookies for Deemix seems to help a lot.

However, when this happens Lidarr no longer is able to communicate with Deemix. I've copied the new ARL from Deemix and pasted it into Lidarr but the Edit Indexer returns the error 'Unable to connect to indexer, check the log for more details' when testing.

I've restarted the containers to see if that will help but it doesn't. I'll paste the current log below.

Here is my docker-compose:

version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    # container_name: sonarr
    # privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data:/config
      - ./data:/config_deemix
      - /mnt/music:/music #optional
      - /sharedDownloads/:/downloads #optional
      - /sharedDownloads/:/data/completed/
    ports:
      - 8686:8686
      - 6595:6595
    restart: unless-stopped

[lazydocker-log-20220702.txt](https://github.com/youegraillot/lidarr-on-steroids/files/9248976/lazydocker-log-20220702.txt)

[lazydocker-log-20220703.txt](https://github.com/youegraillot/lidarr-on-steroids/files/9248995/lazydocker-log-20220703.txt)

**Comment by youegraillot** [comment]
With AUTOCONFIG, you should not have to copy ARL from deemix to lidarr, are you using a separate image for Deemix ?
What do you mean by "clearing the cookies for Deemix", what is your procedure for doing that ?

also do you have a more complete set of logs ? from the ones you uploaded I can't find a plausible cause for your behavior

**Comment by martind2000** [comment]
I'm using the built in Deemix within the image. 'Clearing out the cookies for Deemix', I go to the Deemix instance in the browser, it sits at 'Logging in' and doesn't want to proceed, so in the browser I clear the cookie to try to get it to log back in. Sometimes it works, sometimes it doesn't. Maybe it's not even the clearing of the cookie which helps. Watching the network requests, sometimes it fails to get the login page, sometimes it fails to get other pages. Which log would you want? I found one that was long that has more info I think.

**Comment by youegraillot** [comment]
Full logs of your container would be nice
But my guess ATM is that it is not linked to the image, but your network setup or browser
Having a log of your browser console when you try to login may be more relevant

**Comment by martind2000** [comment]
Watching the Docker Compose log, I can see that Deemix is constantly restarting because a log file is missing.
[lidarr-on-steroids-docker-log.txt](https://github.com/youegraillot/lidarr-on-steroids/files/9274563/lidarr-on-steroids-docker-log.txt)

I also have Deemix in an appimage which I was using before this system and I tested it just to be sure, and that seems to be working ok. It's a little old: Current WebUI Version: 1.9.3, Current Version: 2022.4.28-r202.475ccfc850, deemix lib version: 3.6.9

[Lidarr.txt](https://github.com/youegraillot/lidarr-on-steroids/files/9274565/Lidarr.txt)

There is a time stamped log file in the logs list but that actually doesn't seem to exist.

**Comment by youegraillot** [comment]
Oh got it !
you set both volumes /config and /config_deemix to the same path on your host
which kind of mess things up

These two volumes correspond to very different configurations (Lidarr for /config and Deemix for /config_deemix)
Try with a different mapping and you should be good

**Comment by martind2000** [comment]
oooooh... Ok, I'll give that a try and let you know, cheers.

**Comment by martind2000** [comment]
That's it, changed the mapping and everything's cool now. Thanks for your help, I hadn't noticed I did that.

**Comment by youegraillot** [comment]
Perfect !
