### ISSUE TITLE
No Deemix as option in Indexers

### ISSUE THREAD

**Issue by bcrowie** [youegraillot/lidarr-on-steroids#21]
I am unable to add Deemix as an option in Indexers. I started the docker container per the instructions, I can reach both the Lidarr and the Deemix web UIs, and I have logged into Deemix. But I have no way to add Deemix as an indexer in Lidarr, so this is essentially just Lidarr at this point. I dont see any errors in the logs. Am I missing something? Any help is appreciated!

**Comment by youegraillot** [comment]
Please refer to the README
Deemix won't be added as an indexer, but as a downloader, the only step you have to do is to fill in your deezer credentials
The configuration script will then setup Lidarr for you

**Comment by bcrowie** [comment]
I have added my credentials to deezer, still nothing has been added as a downloader or an indexer. I have also restarted the container with no additional changes.

**Comment by youegraillot** [comment]
What do you see in your logs ?

**Comment by bcrowie** [comment]
`s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-env-file-init
cont-init: info: /etc/cont-init.d/00-env-file-init exited 0
cont-init: info: running /etc/cont-init.d/00-start-container
cont-init: info: /etc/cont-init.d/00-start-container exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun deemix (no readiness notification)
services-up: info: copying legacy longrun lidarr (no readiness notification)
services-up: info: copying legacy longrun setup (no readiness notification)
s6-rc: info: service legacy-services successfully started
----------------------------------------------------------------------
LIDARR SETUP
----------------------------------------------------------------------
PluginSource=https://github.com/ta264/Lidarr.Plugin.Deemix
----------------------------------------------------------------------

[autoconfig] Waiting Lidarr to launch on 8686...
2022-11-27T20:03:43.413Z [info] Listening on port 6595
[Info] Bootstrap: Starting Lidarr - /app/bin/Lidarr.dll - Version 1.1.2.2826 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/lidarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[autoconfig] Installing / Updating Deemix plugin
[autoconfig] Waiting github rate limit reset
[Info] ConsoleApp: Exiting main. 

----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=1000
PGID=1000
UMASK=002
TZ=America/Los_Angeles
----------------------------------------------------------------------

Executing usermod...
usermod: no changes
Applying permissions to /config

----------------------------------------------------------------------
SETUP
----------------------------------------------------------------------
AUTOCONFIG=true
----------------------------------------------------------------------

Changing ownership on scripts.
Changing ownership of /music
[services.d] Starting Deemix
Changing ownership of /downloads

----------------------------------------------------------------------
LIDARR SETUP
----------------------------------------------------------------------
PluginSource=https://github.com/ta264/Lidarr.Plugin.Deemix
----------------------------------------------------------------------

[autoconfig] Waiting Lidarr to launch on 8686...
2022-11-27T20:34:01.260Z [info] Listening on port 6595
[Info] Bootstrap: Starting Lidarr - /app/bin/Lidarr.dll - Version 1.1.2.2826 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/lidarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[autoconfig] Installing / Updating Deemix plugin
[autoconfig] Waiting github rate limit reset
/settings
2022-11-27T20:34:17.746Z [info] Currently running deemix-gui version 2022.8.20-r216.06305de9cf
2022-11-27T20:34:17.747Z [info] deemix-lib version 3.6.11
[Info] RssSyncService: Starting RSS Sync 
[Warn] FetchAndParseRssService: No available indexers. check your configuration. 
[Info] DownloadDecisionMaker: No results found 
[Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0 `

**Comment by youegraillot** [comment]
`[autoconfig] Waiting github rate limit reset`

Because your container has restarted multiple times, you've hit github api limits (we use the api to download the deemix plugin)

Please stop your container, wait 10minutes, and the image should configure lidarr for you once it can download the plugin from github

Kind of my fault, my github api limit wait does not seem to work properly

**Comment by bcrowie** [comment]
> `[autoconfig] Waiting github rate limit reset`
> 
> Because your container has restarted multiple times, you've hit github api limits (we use the api to download the deemix plugin)
> 
> Please stop your container, wait 10minutes, and the image should configure lidarr for you once it can download the plugin from github
> 
> Kind of my fault, my github api limit wait does not seem to work properly

No worries, mate! I'll stop it and give it some time and come back to it in a bit! I appreciate your help.

**Comment by youegraillot** [comment]
I've pushed a better fix for the github api limit
With v1.2.7 you should be able to launch the image and let it wait for you the correct amount of time
