### ISSUE TITLE
[REQ] Dont delete flac after converting

### ISSUE THREAD

**Issue by dvdgorila** [youegraillot/lidarr-on-steroids#28]
Hello youegraillot, 

Not sure if this already exists, is there a way to keep the flac files after they are converted to mp3?

If not can you add this function?

Thanks, 
dvdgorila

**Comment by youegraillot** [comment]
Hey, yes that's a feature of https://github.com/youegraillot/lidarr-flac2mp3
Just add `--keep-file` in `FLAC2CUSTOM_ARGS`
