### ISSUE TITLE
armv7 support

### ISSUE THREAD

**Issue by blaugelbpeter** [youegraillot/lidarr-on-steroids#29]
**Is your feature request related to a problem? Please describe.**
I tried to install this on my raspberry pi 4, but the docker installation fails.

**Describe the solution you'd like**
I would like to be able to install this on my raspberry pi 4.

**Describe alternatives you've considered**
I've tried installing the plugins branch of https://github.com/Lidarr/Lidarr (which this repository is based on, as far as I understand), but Lidarr was not able to start. Installing the master and develop branches works without problems. There was no difference when using the installation script from https://wiki.servarr.com/install-script or the docker image from https://github.com/linuxserver/docker-lidarr. I was able to install both Lidarr and Deemix, so there seem to be some problems related to the plugins branch.

**Comment by youegraillot** [comment]
Are you trying to manually setup everything ?
This image is not intended to be used like that, the 'plugins' branch on Lidarr repository has been forced pushed multiple times, and the version we use here may be different

**Comment by blaugelbpeter** [comment]
Yes, I tried to manually setup everything. When I tried simply running the docker script in the README file, docker was not able to find an armhf image. Afterwards I tried different ways to install Lidarr and Deemix, but could not get the plugins branch running. However, it was easier for me to simply install the arm64 version of Raspberry PI OS and now everything works fine.
