### ISSUE TITLE
clean-downloads script does not clean the downloads folder

### ISSUE THREAD

**Issue by Rincewind-T** [youegraillot/lidarr-on-steroids#42]
**Describe the bug**
The clean-downloads script does not seem to do its work. Downloaded files stay in the download folder even after successful import or after upgrade.

**To Reproduce**
The script is set up via "Custom Scripts" in the "Connect" setting in Lidarr and is triggered "On Release Import" and "On Upgrade". Neither the one nor the other trigger seems to initiate the cleanup of the downloads folder. I am not sure if the script is not triggered correctly or something is wrong with the script itself.

**Expected behavior**
a full cleanup of the download folder after release is fully imported into Lidarr

**System info**
 - Synology NAS
 - docker 20.10.3

_I've never written an issue on GitHub before, so forgive me if I'm a bit clueless. :)_

**Comment by Rincewind-T** [comment]
This is the only reference to the script in the logs:

`2023-02-16 21:40:16.5|Error|clean-downloads.sh|Info|Cleaning empty folders`

**Comment by youegraillot** [comment]
please provide log and your setup (docker-compose.yml or something else) in order for me to help here
it may be related to permissions but I have no way to know
