### ISSUE TITLE
New Released Song/album doesn't get added to lidarr

### ISSUE THREAD

**Issue by Breakingx** [youegraillot/lidarr-on-steroids#46]
**Describe the bug**
Lidarr doesn't list new songs available on deemix/deezer

**To Reproduce**
1. Go to Library
2. Add new 
3. Search for example "Ghostkid" and add the artist
4. A released song from about a week doesn't get listed

**Comment by Redstoneguy129** [comment]
Adding to this.
When i add an artist, and search for monitored songs. It indexes correctly, and sends it to deemix to be downloaded. Deemix shows it as downloading then download complete. The song is never added to lidarr or the music folder.

**Comment by Breakingx** [comment]
Anything new? Songs released months ago doesn't get indexed by lidarr but some others do? Why?

**Comment by codefaux** [comment]
Lidarr depends on external metadata sources. Those external sources may or may not update in a timely fashion. This is not a Lidarr issue.

**Comment by youegraillot** [comment]
out of this scope, ping lidarr devs
