### ISSUE TITLE
PUID and PGID as root?

### ISSUE THREAD

**Issue by wouterverduin** [youegraillot/lidarr-on-steroids#47]
**Describe the bug**
Hi there! Love the idea of the combination of Lidarr and Deemix. However: For my music folder to be reatable/writable i have to use PUID and PGID=0.
When i set that up in docker i get the error in the dokker logs "Running as root is not supported, please fix your PUID and PGID!"
If i switch them back to 1000 i get the error "Folder is not writable by user hotio" in the lidarr web interface when setting up the root folder..
 
**To Reproduce**
1. Fresh docker compose file
2. Click on ubuntu 22.04
3. Change PGID and PUID to either 0 or 1000

**Expected behavior**
possibility to run as root

Is there anyway around this? Would love to use this combination!

**Comment by samip5** [comment]
You should fix your folder permissions and NOT run things as root. :)
