### ISSUE TITLE
ability to search multiple HDDS for a artist

### ISSUE THREAD

**Issue by schwartzaher** [youegraillot/lidarr-on-steroids#49]
I am currently using the regular lidarr, which doesn't have deemix integration like this one. I really like the deemix integration of this one, allowing me to download any artist I want with my ARL. Kudos to whoever made this. Is there a way for me to be able to have an option of it searching multiple hard drives like there is now, but also showing in the artist folder both locations, or is that not able to be added.

Currently I have some artists, due to the way I set things up, as I am stupid, some artists are split between two drive. I would love to be able to have both artist locations show up and fill the artist up with what releases I have. This way if I tell Lidarr to update the artists, it won't redownload stuff that I already own.

**Comment by youegraillot** [comment]
out of this project's scope
