### ISSUE TITLE
is there any aspiration from your side to update the project to a more current lidarr version?

### ISSUE THREAD

**Issue by mason-xx** [youegraillot/lidarr-on-steroids#55]
Is there any aspiration from your side to update the project to a more current lidarr version?
No nagging or anything, just a question.

**Comment by DrMxrcy** [comment]
I forked the repo and updated the version and just rebuilt the container. The newsest version of the plugins branch is working.

**Comment by youegraillot** [comment]
@DrMxrcy Do not hesitate to submit a pull request so people using this image have the update if it work
