### ISSUE TITLE
"Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. Connection refused"

### ISSUE THREAD

**Issue by unvency** [youegraillot/lidarr-on-steroids#71]
When trying to Deemix as Indexer or also as Downloader, I am getting an error (both on a Windows PC and on an Ubuntu server).

The command on the Linux server was:
`podman run  --name lidarr  -p 127.0.0.1:8686:8686  -p 127.0.0.1:6595:6595 -v /mnt/lidarr/config:/config -v /mnt/lidarr/music:/music -v /mnt/lidarr/downloads:/downloads  -v /mnt/lidarr/config_deemix:/config_deemix --restart unless-stopped localhost/lidarr`

(Don't wonder; I renamed youegraillot/lidarr-on-steroids to localhost/lidarr)

Any ideas what to do?

**Comment by yannik995** [comment]
Duplicate to #63

**Comment by youegraillot** [comment]
https://github.com/youegraillot/lidarr-on-steroids/pull/65 has been merged
closing
