### ISSUE TITLE
Arm image on Docker fails to initialise patched Deemix

### ISSUE THREAD

**Issue by noworthwhile** [youegraillot/lidarr-on-steroids#72]
After pulling the new image, it seems the Deemix part of the image is not created correctly

`s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
jq: error: Could not open file /config_deemix/login.json: No such file or directory
[services.d] Starting Deemix
s6-applyuidgid: fatal: unable to exec /deemix-server: Exec format error
`

Any ideas?

**Comment by youegraillot** [comment]
please respect the bug report template
without hardware info or legible logs, we cannot help

**Comment by noworthwhile** [comment]
My apologies,

Here are the information required:

**Describe the bug**
The patched docker image for Arm64 fails to initialise the Deemix part of the image, with logs shown above.

**To Reproduce**
Use a RaspberryPi 4 2 Gb, with an USB SSD 128 gb as a boot drive.
Fully updated, so is Docker and Docker-compose.

Use the docker-compose.yml that is provided, docker compose up then check the logs or try to access Deemix web-ui

**Expected behavior**
Access to Deemix web-ui.

**Screenshots**
N/A, see logs above.

**System info (please complete the following information):**
 - OS: Raspbian
 - Container engine 20.10.21 on linux/arm64

**docker-compose.yml (please complete the following information):**

version: "3"
services:
  lidarr:
    image: youegraillot/lidarr-on-steroids:latest
    restart: unless-stopped
    ports:
      - "8686:8686"
      - "6595:6595"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - AUTOCONFIG=true
    volumes:
      - /home/docker/lidarr/config:/config
      - /home/docker/lidarr/config_deemix:/config_deemix
      - /home/data/downloads/:/downloads
      - /home/data/music:/music
    network_mode: bridge
      
```
Maybe I'm missing something?

Thanks

**Comment by estebanthi** [comment]
I have the same issue on my Raspberry Pi. I tried to build `deemix-gui` from https://gitlab.com/RemixDev/deemix-gui but could not build it out of the box and had to add some dependencies. When I finally managed to build it, the executable was not working. Not sure but I guess it's an issue related to missing dependencies.

**Comment by estebanthi** [comment]
Sure. I've restarted my lidarr container, and here are the logs.
[_lidarr_logs.txt](https://github.com/youegraillot/lidarr-on-steroids/files/12600299/_lidarr_logs.txt)

**Comment by youegraillot** [comment]
Ok, think I got this, arm binaries did get build as amd64
Can you try out v1.5.1 ?

**Comment by estebanthi** [comment]
Works perfectly now. Thanks!
