### ISSUE TITLE
Can't import some tracks/albums

### ISSUE THREAD

**Issue by hamidout** [youegraillot/lidarr-on-steroids#8]
Thank you for this project.

Some albums won't import due to some errors like:

- Has unmatched tracks
- Album match is not close enough: 59.3 % vs 80 % [album, media count, year, country, tracks, unmatched tracks]
- Couldn't find similar album for [/downloads/x/x]

I'm using all the stock settings, only configured the ARL.

![image](https://user-images.githubusercontent.com/66022183/180247621-2e687b8c-582c-4ef3-892c-52add8066509.png)
![image](https://user-images.githubusercontent.com/66022183/180247652-a05ba944-898d-4537-9dc5-05f27071893c.png)

**Comment by youegraillot** [comment]
Does this occurs when you import from Deemix or from your own files ?
Lidarr uses MusicBrainz as a metadata indexer, and MusicBrainz is incomplete
If you can't find your record on MusicBrainz, you won't be able to import these into Lidarr

FYI I'm working on a way to get deezer as a metadata source as well

**Comment by youegraillot** [comment]
If you can't find your album on MusicBrainz, there is no way to fix that for the moment
I hope to get deezer indexing available soon ;)

**Comment by ItsNoted** [comment]
> 

This would be great because I like a lot of obscure artists like Shaheen Fahmy that do film scores etc that are NOT indexed on musicbrainz so they cannot be imported by Lidarr. I hope you find a solution for this. Thank you!

**Comment by DrMxrcy** [comment]
The same issue is happening to me. I hope you can get something to work to fix matches!
