### ISSUE TITLE
Deemix gives error "EACCES: permission denied, mkdir"

### ISSUE THREAD

**Issue by Carter0108** [youegraillot/lidarr-on-steroids#9]
I've installed the dockerhub image on my TrueNAS Scale server but Deemix doesn't seem to have write permissions so all downloads are failing.

**Comment by youegraillot** [comment]
You're actually the second person to open an issue for this, I'm not familiar with TrueNAS but it seems recurrent
Would you be able to share some logs ? I'm particlarly interested on the puid/guid mapping on your device

**Comment by hamidout** [comment]
I actually had the same issue but using docker on Debian.
For some reason the `downloads` folder gets created with the owner `root`, while the other folders are created as the normal user.
To fix it you just need to change the owner of the downloads folder (`chown -R $USER:$USER downloads/`).
I am unsure what causes this issue to begin with.

**Comment by youegraillot** [comment]
Thanks for the details @hamidout, I'll check that
Do you use the provided docker-compose example ? I've only tested this on docker (windows) and podman rootless

**Comment by youegraillot** [comment]
This is fixed by a4b7cfb4f35785e3b3604aa359b29fce28675c79
